/* ============================================
   IRB — Protocol Draft Generator UI
   Shown on any submission detail view where
   compliance.humanSubjects is true.
   ============================================ */

function renderIRBSection(sub) {
  const card = document.createElement('div');
  card.className = 'card irb-card';
  card.style.marginTop = '16px';

  if (sub.irbDraft) {
    // Already generated — show the draft
    card.innerHTML = `
      <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px;margin-bottom:16px">
        <div>
          <div class="card-title">📋 IRB Protocol Draft</div>
          <div style="font-size:0.75rem;color:var(--text-muted);margin-top:2px">Generated by Grant AI · Review all [PLACEHOLDER] items before submitting</div>
        </div>
        <div style="display:flex;gap:8px">
          <button class="btn btn-secondary btn-sm" onclick="copyIRBDraft('${sub.id}')">📋 Copy</button>
          <button class="btn btn-secondary btn-sm" onclick="exportIRBPdf(st.submissions.find(s=>s.id==='${sub.id}'))">📄 PDF</button>
          <button class="btn btn-secondary btn-sm" onclick="regenerateIRB('${sub.id}')">↻ Regenerate</button>
        </div>
      </div>
      <div class="irb-draft-body" id="irbBody-${sub.id}">${_renderIRBMarkdown(sub.irbDraft)}</div>
    `;
  } else {
    // Not yet generated
    card.innerHTML = `
      <div style="display:flex;gap:16px;align-items:flex-start">
        <div style="font-size:2rem;flex-shrink:0">📋</div>
        <div style="flex:1">
          <div class="card-title" style="margin-bottom:6px">IRB Protocol — Human Subjects Review Required</div>
          <p style="font-size:0.83rem;color:var(--text-secondary);line-height:1.6;margin-bottom:14px">
            This proposal involves human subjects research. IRB approval is required before any data collection begins.
            Grant can draft a complete IRB protocol outline — all 13 sections — tailored to this proposal.
            You'll get a document ready to take straight to your IRB office.
          </p>
          <div style="display:flex;gap:10px;align-items:center;flex-wrap:wrap">
            <button class="btn btn-primary" id="irbGenBtn-${sub.id}" onclick="generateIRBDraft('${sub.id}')">
              Generate IRB Protocol Draft →
            </button>
            <span style="font-size:0.75rem;color:var(--text-muted)">~30 seconds · saves automatically</span>
          </div>
          <div id="irbOutput-${sub.id}" style="margin-top:14px"></div>
        </div>
      </div>
    `;
  }

  return card;
}

// ── Generation ────────────────────────────────────────────────────────────────

async function generateIRBDraft(subId) {
  const sub = st.submissions.find(s => s.id === subId);
  if (!sub) return;

  const btn    = document.getElementById('irbGenBtn-' + subId);
  const output = document.getElementById('irbOutput-' + subId);

  if (btn) { btn.disabled = true; btn.textContent = 'Generating…'; }
  if (output) output.innerHTML = `
    <div style="text-align:center;padding:20px;color:var(--text-muted);font-size:0.83rem">
      <div style="font-size:1.5rem;margin-bottom:8px">📋</div>
      Grant is drafting your IRB protocol — all 13 sections…
    </div>`;

  try {
    const res = await fetch('/.netlify/functions/generate-irb', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json' },
      body:    JSON.stringify({ submission: sub })
    });
    const data = await res.json();
    if (!res.ok) throw new Error(data.error || 'Generation failed');

    await saveIRBDraft(subId, data.draft);
    // onSnapshot will auto-refresh the detail view with the saved draft
    // Also update immediately so the user doesn't have to wait
    if (output) output.innerHTML = _renderIRBMarkdown(data.draft);

    GRANT_TTS.speak('Your IRB protocol draft is ready. It covers all 13 sections. Review the bracketed placeholders and fill them in before submitting to your IRB office.');
  } catch (err) {
    if (output) output.innerHTML = `<div style="color:#f87171;font-size:0.83rem">Generation failed: ${err.message}. Please try again.</div>`;
    if (btn) { btn.disabled = false; btn.textContent = 'Generate IRB Protocol Draft →'; }
  }
}

async function regenerateIRB(subId) {
  if (!confirm('Regenerate the IRB draft? This will replace the current version.')) return;
  const sub = st.submissions.find(s => s.id === subId);
  if (!sub) return;
  // Temporarily clear the draft so the card shows the generation state
  await saveIRBDraft(subId, null);
  // render() will be triggered by onSnapshot — then user clicks generate again
}

// ── Copy to clipboard ─────────────────────────────────────────────────────────

function copyIRBDraft(subId) {
  const sub = st.submissions.find(s => s.id === subId);
  if (!sub?.irbDraft) return;
  navigator.clipboard.writeText(sub.irbDraft).then(() => {
    const btn = document.querySelector(`button[onclick="copyIRBDraft('${subId}')"]`);
    if (btn) { btn.textContent = '✓ Copied'; setTimeout(() => { btn.textContent = '📋 Copy'; }, 2000); }
  });
}

// ── Markdown renderer ─────────────────────────────────────────────────────────
// Converts the Gemini-generated markdown into clean HTML for display.
// Handles: # H1, ## H2, ### H3, **bold**, - bullets, [PLACEHOLDER] highlights

function _renderIRBMarkdown(text) {
  if (!text) return '';
  return text
    .split('\n')
    .map(line => {
      if (line.startsWith('# '))   return `<h2 class="irb-h1">${_inline(line.slice(2))}</h2>`;
      if (line.startsWith('## '))  return `<h3 class="irb-h2">${_inline(line.slice(3))}</h3>`;
      if (line.startsWith('### ')) return `<h4 class="irb-h3">${_inline(line.slice(4))}</h4>`;
      if (line.startsWith('- '))   return `<div class="irb-bullet">• ${_inline(line.slice(2))}</div>`;
      if (line.startsWith('☐ '))   return `<div class="irb-check">☐ ${_inline(line.slice(2))}</div>`;
      if (line.trim() === '---')   return `<hr class="irb-divider">`;
      if (line.trim() === '')      return `<div style="height:6px"></div>`;
      return `<p class="irb-p">${_inline(line)}</p>`;
    })
    .join('');
}

function _inline(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\[([^\]]+)\]/g, '<span class="irb-placeholder">[$1]</span>');
}

// ── PDF Export ────────────────────────────────────────────────────────────────
// Called from the Copy/PDF row in the rendered card.
// Takes the raw markdown text and generates a formatted PDF.

function exportIRBPdf(sub) {
  if (!sub?.irbDraft) { alert('No IRB draft to export.'); return; }
  if (!window.jspdf)  { alert('PDF library not loaded. Please refresh and try again.'); return; }

  const { jsPDF } = window.jspdf;
  const doc    = new jsPDF({ unit: 'mm', format: 'letter' });
  const W      = doc.internal.pageSize.getWidth();
  const H      = doc.internal.pageSize.getHeight();
  const margin = 16;
  const cw     = W - margin * 2;
  let y        = 0;

  const checkPage = (needed = 10) => {
    if (y + needed > H - 20) { doc.addPage(); y = 20; }
  };

  // ── Header ──
  doc.setFillColor(26, 58, 107);
  doc.rect(0, 0, W, 36, 'F');
  doc.setTextColor(253, 185, 39);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.text('NC AGRICULTURAL & TECHNICAL STATE UNIVERSITY · CAES', margin, 11);
  doc.text('OFFICE OF SPONSORED PROGRAMS — IRB PROTOCOL OUTLINE', margin, 17);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(13);
  doc.text('IRB Protocol Draft', margin, 29);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'})}`, W - margin, 29, { align: 'right' });

  y = 44;
  doc.setTextColor(20, 20, 20);

  // ── Parse and render markdown lines ──
  const lines = sub.irbDraft.split('\n');
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line === '---') { y += 3; continue; }

    if (line.startsWith('# ')) {
      checkPage(14);
      doc.setFontSize(12); doc.setFont('helvetica', 'bold'); doc.setTextColor(26, 58, 107);
      const wrapped = doc.splitTextToSize(line.slice(2), cw);
      doc.text(wrapped, margin, y); y += wrapped.length * 6 + 4;
    } else if (line.startsWith('## ')) {
      checkPage(12);
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(26, 58, 107);
      doc.setFillColor(240, 245, 255);
      const label = line.slice(3).replace(/\*\*/g, '');
      doc.rect(margin - 2, y - 5, cw + 4, 8, 'F');
      doc.text(label, margin, y); y += 9;
    } else if (line.startsWith('### ')) {
      checkPage(9);
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(40, 40, 40);
      doc.text(line.slice(4).replace(/\*\*/g, ''), margin, y); y += 7;
    } else if (line.startsWith('- ') || line.startsWith('☐ ')) {
      checkPage(7);
      doc.setFontSize(8.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(50, 50, 50);
      const txt = '• ' + line.slice(2).replace(/\*\*/g, '').replace(/\[([^\]]+)\]/g, '[$1]');
      const wrapped = doc.splitTextToSize(txt, cw - 5);
      doc.text(wrapped, margin + 3, y); y += wrapped.length * 5 + 2;
    } else if (line.startsWith('**') && line.endsWith('**')) {
      checkPage(8);
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(30, 30, 30);
      doc.text(line.replace(/\*\*/g, ''), margin, y); y += 7;
    } else {
      checkPage(7);
      doc.setFontSize(8.5); doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60);
      const clean = line.replace(/\*\*(.+?)\*\*/g, '$1');
      const wrapped = doc.splitTextToSize(clean, cw);
      doc.text(wrapped, margin, y); y += wrapped.length * 5 + 1;
    }
    doc.setTextColor(20, 20, 20);
  }

  // ── Footer on every page ──
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7); doc.setTextColor(150, 150, 150); doc.setFont('helvetica', 'normal');
    doc.text('Grant Assistant AI · NC A&T CAES Office of Sponsored Programs · IRB DRAFT — NOT FOR SUBMISSION', margin, H - 8);
    doc.text(`Page ${i} of ${pages}`, W - margin, H - 8, { align: 'right' });
  }

  doc.save(`IRB_Draft_${(sub.title || 'proposal').replace(/[^a-z0-9]/gi, '_').substring(0, 40)}.pdf`);
}
